### ISSUE TITLE
Develop branch install - Fatal Error 

### ISSUE THREAD

**Issue by namenodeis** [CircleBilling/CircleBilling#12]
I was trying to test the development version with php 7.2...
On visiting the /install directory on a webhost I prepared, I get stopped on the following error:
```Fatal error: Uncaught Error: Class 'Box_Requirements' not found in /home/user/public_html/src/install/index.php:131 Stack trace: #0 /home/user/public_html/src/install/index.php(517): Installer->run('index') #1 {main} thrown in /home/user/public_html/src/install/index.php on line 131```

This is running on a shared webhost with Apache/Nginx/Varnish configuration installed with PHP 7.2.
I ran composer install inside vagrant on my local machine. I then zipped the src directory and uploaded it to an account I prepared for the purpose.

**Comment by Eiskaltereistee** [comment]
Hi @namenodeis,
thank you for posting this issue.

Can you check if the file `/src/bb-library/Box/Requirements.php` exists? 

Also you can help me to find the problem:
Insert `var_dump(get_include_path());` into src/install/index.php line 47 (Like above `require BB_PATH_VENDOR . '/autoload.php';`) and post the output to this issue.

**Comment by namenodeis** [comment]
Requirements.php does exist there. 

I added the line on 46 per your instruction. Here is the output: 
```string(71) "/home/user/public_html/src/bb-library:.:/usr/local/lib/php" ```
```Fatal error: Uncaught Error: Class 'Box_Requirements' not found in /home/user/public_html/src/install/index.php:131 Stack trace: #0 /home/user/public_html/src/install/index.php(517): Installer->run('index') #1 {main} thrown in /home/user/public_html/src/install/index.php on line 131```

**Comment by Eiskaltereistee** [comment]
Thank you.

It looks like you have a problem in your composer autoloader. Can you please delete all files in src/bb-vendor (`rm -rf src/bb-vender/*`).
Then run composer install in the main directory in the vagrant vm.

After that you can upload the files again and test.

If it's still not working, please zip and upload your src directory.

**Comment by namenodeis** [comment]
Well done! 

That gets me to the install page. I will continue to add issues as I find them.

Cheers CB team!

**Comment by Eiskaltereistee** [comment]
Glad, that I could help.

I will close this issue. Thank you for helping us! We are happy to have you with us.
