### ISSUE TITLE
Query About CircleBilling

### ISSUE THREAD

**Issue by kieran2001** [CircleBilling/CircleBilling#15]
What’s the current state of CircleBilling / what has being changed from the original BoxBilling fork?

Also, where is the best place to communicate in real time my thoughts and ideas about this software?

**Comment by 62BRAINS** [comment]
Hello @kieran2001,

Our focus is on fixing bugs and achieving a stable version. After we get to that stage, other enhancements, features, adjustments may be made. You can always comment here or on the forum at https://forum.circlebilling.com/

Thank you for inquiring. We are progressing and look forward to hearing more of your thoughts.

**Comment by kieran2001** [comment]
Is this in a usable state at the moment, will this software be free/open source and will there be some tool or easy way to migrate from B.B. to C.B? 

I currently run a free web host, so keeping costs down is incredibly important, but BoxBilling is far from perfect, for example the affiliate program doesn’t exist, there’s no community, there’s biazzare errors, there little / badly designed themes and other such missing features.

What I’d love C.B. to be, is something that’s free and halfway between B.B & WHMCS.

**Comment by 62BRAINS** [comment]
It isn't usable at this time, but we are diligently looking at reported problems and are attempting to get to a usable and trustworthy version. We have briefly touched on migration, but cannot state with certainty at this time what will come of that.

We understand your needs well and do hope you will find Circle Billing to meet your needs when it is ready. Circle Billing is open source and it is very nice that you shared your comments and desires. Follow us. We'll post news as it develops.

**Comment by kieran2001** [comment]
Is there anything I can do to help? Such as phrasing for tool tips or similar, making repetitive changes such as changing any reference to B.B. to C.B. or anything else along those lines, suggestion for installer or migration systems etc?

**Comment by Eiskaltereistee** [comment]
Hi @kieran2001,
sure, you can help us!

Some things we really need:
- A test database (Filled with some test clients, products, invoices, knowledge and forum): You can checkout the bugfixing brach and run the installer.
- Reviews and tests! - If you want, you can checkout the bugfixing branch and test the whole functionality: If you found a bug, you can create a issue.
- If you already fixed bugs for boxbilling, you can have a look if it's already fixed in our "bugfixing" branch. If not, create a pull request.

Thank you for the support. We are happy to see the growing community.

**Comment by StefvanEgmond** [comment]
And don't forget we need a bigger community!

**Comment by kieran2001** [comment]
When is an initial release expected?

**Comment by Eiskaltereistee** [comment]
@kieran2001 this is a free open source project, so all of us investing their free time. 
We do not want to commit ourselves, but I have the hope to release a stable version in a couple of weeks.

**Comment by OnlyHardOfficial** [comment]
@kieran2001 Here is a tutorial that you can follow as a reference to install the panel there in your machine and give us a help https://forum.circlebilling.com/thread-7-post-32.html#pid32
