### ISSUE TITLE
Add translation of all texts

### ISSUE THREAD

**Issue by OnlyHardOfficial** [CircleBilling/CircleBilling#18]
Well, my request is directly related to a problem of subtitles/mistranslation! Not because the Softwer itself is not far from 100% translated!But something is still missing for this to happen
I would say that overall it contains 75% 80% translated. Because there are Modules that do not have the included translation variable, the default language "messages.po" also does not include its translation!
Anyway, I am creating here a file in Microsoft Excel pointing out which modules, line and variable is missing, so that something similar does not happen

I'm working on a "trying" to complete the most comprehensive translation of all the possible and imaginary words that are written inside the softwer!
I will include the missing words in English and Portuguese and then cover all other languages!

And for this reason, we should all focus at this time on maintaining only a single theme on the client side!
We must delete the folder of the theme "huraga". Because at the moment we have two themes and the default is the [inappropriate theme](https://i.gyazo.com/bc828a668d7a78b0586cdc5cd7e9beb1.png) due to the lack of all the resources!
The "huraga" theme is a theme released but incomplete in terms of code [like this](https://i.gyazo.com/ae78f64277c86912b2dad4e1e72e43fb.jpg)

**Comment by gOOvER** [comment]
If needed, i will help you.

**Comment by Eiskaltereistee** [comment]
I would be very happy if there are some guys who creating custom themes. Maybe, if we have 2 / 3, we can create a "store" page where users can download themes and extensions(plugins, modules).

In the last step, we can create a new working auto installer, so users can install themes and extensions directly in the admin backend from the "store".
