### ISSUE TITLE
Website / Backend Connection

### ISSUE THREAD

**Issue by kieran2001** [CircleBilling/CircleBilling#20]
Will CircleBilling have a simple front end to backend connection, with static sites?

For example, WHMCS will automatically pass details through from a login form on your main website, as long as you use the dologin.php File.  I don’t believe BoxBilling has this.

Also, will this project be a constant one, with updates at least once or twice a year, and not being left for almost 5 years with nothing more than a statement saying not enough demand (highly doubt it for free) which BoxBilling has now done.

As even without demand, security patches and small updates should still occur, otherwise your user base will simply leave, and if there’s paid users, revenue would be lost etc.

**Comment by kieran2001** [comment]
Alright, also will there be a cPanel hook for auto-login? I’ve come across a theme on github for BoxBilling (will they be compatible with circlebilling?) and it has a cpanel hook, but stock BoxBilling does not.

**Comment by StefvanEgmond** [comment]
Please consider using the forum for ideas!
