### ISSUE TITLE
[Feature] Laravel framework

### ISSUE THREAD

**Issue by feardevilz** [CircleBilling/CircleBilling#27]
I realize BoxBilling presented a lot of critical fixes which you're working on but I've been looking at the laravel base. What are some of your thoughts on migrating frameworks? How much of a pain would it be to move something like BoxBilling to it?

**Comment by Eiskaltereistee** [comment]
I think it's not really possible. If we would migrate to a framework like laravel, we need to rewrite the whole source code...
