### ISSUE TITLE
Adding translations to Transifex

### ISSUE THREAD

**Issue by gOOvER** [CircleBilling/CircleBilling#4]
When translation would be hosted on Transifex, it would be easier to translate to other languages.

https://www.transifex.com/

**Comment by Eiskaltereistee** [comment]
@gOOvER thank you for your input! We will discuss that.

**Comment by StefvanEgmond** [comment]
Hey, thanks you for your feedback. I think it is not an option because of the pricing. Our top priorities are making CircleBilling compatible with PHP 7.+ and fixing bugs. We may be looking for a free alternative later.

**Comment by kayazeren** [comment]
Transifex free for Open Source projects. But their policy causes problems if the product have a paid "pro" version. So many deveopers moved to [weblate](https://weblate.org).

**Comment by OnlyHardOfficial** [comment]
@kayazeren tanks mate!

**Comment by gOOvER** [comment]
@StefvanEgmond For Opensource it's free ;)
