### ISSUE TITLE
Feature request: Better order status  for onetime orders

### ISSUE THREAD

**Issue by mpoloskey** [CircleBilling/CircleBilling#41]
When a payment is completed, ontime and recurring orders are getting the same order status "active"

I suggest to give a ontime payment orders a different like  status  "completed" so when we search for a active order we only see the recurring orders.

**Comment by StefvanEgmond** [comment]
Hey, thanks for your feedback!
We recently decided to move feature requests to the forums. I moved it to the following topic:
[https://forum.circlebilling.com/thread-16.html](https://forum.circlebilling.com/thread-16.html)
