### ISSUE TITLE
Are you searching for developers?

### ISSUE THREAD

**Issue by nuxwin** [CircleBilling/CircleBilling#9]
Are you searching for developers? If so:

1. What is your current roadmap, schedule? 
2. What is your code of conduct and your coding standard policy?
3. What is your workflow, design? DDD in mind or?
4. Do you plan to work with any framework such as ZF3 or Symfony for development ease?
5. Do you plan to switch to Doctrine for Object-relational mapping?

Thank you.

**Comment by 62BRAINS** [comment]
Hello Nuxwin,

We are currently establishing many of the facets you ask about. We are interested in expanding the development base but wish to do so with a working release. 

There is much to do yet as we decouple and clean up known problems and any new ones that present as we progress.

1) Our current roadmap is in its beginning state with a primary milestone of Circle Billing v1.0 - a tested and working version. We will publish a more comprehensive roadmap as we are able to decipher needs and clear known issues.

2) Our coding standards will be PSR-2. Code of conduct is currently in draft form and we will release that soon. It will be as any developer might expect.

3) We have no hard and fast workflow/design methodology established at this time. We are evaluating possibilities and perhaps Domian Driven Design would fit. Thank you for suggesting it.

4) At this time we are not planning to add in any frameworks. We desire to understand the current code base fully before introducing any layers or to restructure existing code to work with a framework. I am not saying it won't happen, but we agree right now to not use a given framework.

5) Do time and ORM are interesting possibilities, and may be of value. I can see some advantages there in the future. Just getting to stable is our primary focus. Nothing is completely off the table at this time.

Thank you for expressing interest and for sharing your insight into the possibilities before us. I look forward to communicating again soon.

**Comment by nuxwin** [comment]
@62BRAINS 

Thank you for your clarification. That is much appreciated.
I'll continue follow you and perhaps contribute with some PR in near future.

**Comment by gOOvER** [comment]
@nuxwin Nice the hear :) 

Nuxwin is a great Developer :) and i bet he do some great PR's :)
